/**
 * The little person every agent renders as. 16x24 frames, anchor at the feet
 * (bottom-center). All standing/walking/sitting frames FACE RIGHT — the
 * runtime pre-flips for left-facing.
 *
 * Palette keys are a runtime contract (swapped per agent):
 *   o outline · s skin · h hair · b outfit base · d outfit shade
 *   a project accent (scarf/stripe) · w white glint
 */
import type { SpriteSheet } from "../pixel";

export const CHARACTER: SpriteSheet = {
	palette: {
		o: "#0A0613", // ink outline
		s: "#F2C29E", // skin
		h: "#0A0613", // hair
		b: "#E8825A", // outfit base (coral)
		d: "#261D46", // outfit shade (dusk)
		a: "#2DE2E6", // project accent (scarf)
		w: "#F2EEFF", // white glint
	},
	anchor: { x: 8, y: 23 },
	frames: {
		// ---- idle: 1px breathing bob ----
		"idle.0": [
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaaao....",
			"...obbbbbbbbo...",
			"...odbbbbbbdo...",
			"...odbbbbbbdo...",
			"...osbddddbso...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....ooo.ooo....",
		],
		"idle.1": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaaao....",
			"...obbbbbbbbo...",
			"...odbbbbbbdo...",
			"...osbddddbso...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....ooo.ooo....",
		],
		// ---- walk cycle facing right: contact / down / pass / up ----
		"walk.0": [
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaaao....",
			"...obbbbbbbbo...",
			"...odbbbbbbdo...",
			"...odbbbbbbdo...",
			"...osbddddbso...",
			"....oddddddo....",
			".....oddoddo....",
			"....oddooddo....",
			"....oddo.oddo...",
			"...oddo..oddo...",
			"...oddo...oddo..",
			"...oddo...oddo..",
			"...ooo.....oooo.",
		],
		"walk.1": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaaao....",
			"...obbbbbbbbo...",
			"...odbbbbbbdo...",
			"...osbddddbso...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			"....oddo.oddo...",
			"....oddo.oddo...",
			"....oddo.oddo...",
			"....oddo.oddo...",
			"....ooo...oooo..",
		],
		"walk.2": [
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaaao....",
			"...obbbbbbbbo...",
			"...odbbbbbbdo...",
			"...odbbbbbbdo...",
			"...osbddddbso...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			"....oddooddo....",
			"....ooo.oddo....",
			"........oddo....",
			"........oddo....",
			"........oooo....",
		],
		"walk.3": [
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaaao....",
			"...obbbbbbbbo...",
			"...odbbbbbbdo...",
			"...odbbbbbbdo...",
			"...osbddddbso...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			"....oddooddo....",
			"....oddo.oddo...",
			"...oddo..oooo...",
			"...oddo.........",
			"..oddo..........",
			"..ooo...........",
		],
		// ---- seated at desk, profile facing right, typing ----
		"sit.type.0": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaao.....",
			"....obbbbboooo..",
			"....odbbbbbbss..",
			"....odbbbboooo..",
			"....odddddddo...",
			"....oooooooddo..",
			"..........oddo..",
			".........ooooo..",
		],
		"sit.type.1": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaao.....",
			"....obbbbbooso..",
			"....odbbbbbbos..",
			"....odbbbboooo..",
			"....odddddddo...",
			"....oooooooddo..",
			"..........oddo..",
			".........ooooo..",
		],
		"sit.type.2": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".....oooooo.....",
			"....ohhhhhho....",
			"....ohhsssso....",
			"....ohsososo....",
			"....ohsososo....",
			".....osssso.....",
			"....oaaaaao.....",
			"....obbbbbooos..",
			"....odbbbbbbso..",
			"....odbbbboooo..",
			"....odddddddo...",
			"....oooooooddo..",
			"..........oddo..",
			".........ooooo..",
		],
		// ---- slouched on the couch, facing right ----
		"sit.couch.0": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"....oooooo......",
			"...ohhhhhho.....",
			"...ohhsssso.....",
			"...ohsososo.....",
			"...ohsososo.....",
			"....osssso......",
			"...oaaaaao......",
			"..obbbbbbbo.....",
			"..odbbbbbbosdo..",
			"..odbbbbbbdddo..",
			"..oooooooooddo..",
			"..........oooo..",
		],
		"sit.couch.1": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"....oooooo......",
			"...ohhhhhho.....",
			"...ohhsssso.....",
			"...ohsososo.....",
			"...ohsososo.....",
			"....osssso......",
			"...oaaaaao......",
			"..obbbbbbbosdo..",
			"..odbbbbbbdddo..",
			"..oooooooooddo..",
			"..........oooo..",
		],
		// ---- right arm raised straight above head (wave in .1) ----
		"raise.0": [
			"...........ooo..",
			"...........oso..",
			"...........oso..",
			"...........obo..",
			"...........obo..",
			".....ooooooobo..",
			"....ohhhhhhobo..",
			"....ohhssssobo..",
			"....ohsososobo..",
			"....ohsososobo..",
			".....ossssoobo..",
			"....oaaaaaaobo..",
			"...obbbbbbbbbo..",
			"...odbbbbbbbo...",
			"...odbbbbbbbo...",
			"...osbddddbbo...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....ooo.ooo....",
		],
		"raise.1": [
			"............ooo.",
			"............oso.",
			"...........oso..",
			"...........obo..",
			"...........obo..",
			".....ooooooobo..",
			"....ohhhhhhobo..",
			"....ohhssssobo..",
			"....ohsososobo..",
			"....ohsososobo..",
			".....ossssoobo..",
			"....oaaaaaaobo..",
			"...obbbbbbbbbo..",
			"...odbbbbbbbo...",
			"...odbbbbbbbo...",
			"...osbddddbbo...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....ooo.ooo....",
		],
		// ---- confused: head tilted, hand scratching head ----
		"confused.0": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"......oooooo....",
			".....ohhhhhhoso.",
			".....ohhssssoso.",
			".....ohsososobo.",
			".....ohsososobo.",
			"......ossssoobo.",
			"....oaaaaaao.bo.",
			"...obbbbbbbbbbo.",
			"...odbbbbbbbo...",
			"...odbbbbbbbo...",
			"...osbddddbbo...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....ooo.ooo....",
		],
		"confused.1": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"......oooooo....",
			".....ohhhhhho...",
			".....ohhssssoso.",
			".....ohsosososo.",
			".....ohsososobo.",
			"......ossssoobo.",
			"....oaaaaaao.bo.",
			"...obbbbbbbbbbo.",
			"...odbbbbbbbo...",
			"...odbbbbbbbo...",
			"...osbddddbbo...",
			"....oddddddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....oddoddo....",
			".....ooo.ooo....",
		],
	},
};

/**
 * Lying-down sleep frames: 24x16, head to the LEFT, body under a blanket.
 * Extra key: g = pillow (slate) — not part of the swap contract.
 */
export const SLEEP: SpriteSheet = {
	palette: {
		o: "#0A0613",
		s: "#F2C29E",
		h: "#0A0613",
		b: "#E8825A",
		d: "#261D46",
		a: "#2DE2E6",
		w: "#F2EEFF",
		g: "#34315E", // pillow
	},
	anchor: { x: 12, y: 15 },
	frames: {
		"sleep.0": [
			"........................",
			"........................",
			"........................",
			"........................",
			"........................",
			"..ooooo.................",
			".ohhssso................",
			"ohhsoosooooooo..........",
			"ohhssssobbbbaaoooooo....",
			"ohhssssobbbbaabbbbbboo..",
			".ohhsssobbbbaabbbbbbbo..",
			"..oooooobbbbaabbbbbbbo..",
			"ogggggggobbbaabbbbbbbo..",
			"ogggggggobbbaabbbbbbbo..",
			"ogggggggodddaadddddddo..",
			"oooooooooooooooooooooo..",
		],
		"sleep.1": [
			"........................",
			"........................",
			"........................",
			"........................",
			"........................",
			"..ooooo.................",
			".ohhsssooooooo..........",
			"ohhsoosobbbbaao.........",
			"ohhssssobbbbaaoooooo....",
			"ohhssssobbbbaabbbbbboo..",
			".ohhsssobbbbaabbbbbbbo..",
			"..oooooobbbbaabbbbbbbo..",
			"ogggggggobbbaabbbbbbbo..",
			"ogggggggobbbaabbbbbbbo..",
			"ogggggggodddaadddddddo..",
			"oooooooooooooooooooooo..",
		],
	},
};
