/**
 * Back-wall decor for the 384x216 room (wall is y=0..96). All sheets are
 * wall-mounted with a top-left {x:0, y:0} anchor; they are drawn once into
 * the pre-rendered background (the SIGN letters / SKYLINE layers are also
 * used by the animated overlays).
 */

import type { SpriteSheet } from "../pixel";
import { PAL } from "../palette";

/** Shared palette: structural darks + the few neon accents the wall uses. */
const P = {
	k: PAL.ink,
	N: PAL.night,
	D: PAL.dusk,
	L: PAL.slate,
	S: PAL.steel,
	A: PAL.lilac,
	W: PAL.white,
	c: PAL.neonCyan,
	C: PAL.deepCyan,
	B: PAL.holoBlue,
	m: PAL.neonMagenta,
	M: PAL.deepMagenta,
	O: PAL.neonOrange,
	v: PAL.neonViolet,
};

/**
 * 104x56 wall-mounted window: 3px steel frame, white rivets, transparent
 * inside (sky/skyline/rain composited behind by code), 2px sill.
 */
export const WINDOW_FRAME: SpriteSheet = {
	palette: P,
	anchor: { x: 0, y: 0 },
	frames: {
		frame: [
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSk",
			"kSWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWSk",
			"kSSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALSSk",
			"kSSAkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSWAk..............................................................................................kLWSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAk..............................................................................................kLSSk",
			"kSSAkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkLSSk",
			"kSSLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLSSk",
			"kSWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWSk",
			"kSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
		],
	},
};

/**
 * Parallax city layers behind the window, each 98x40, stacked far -> mid
 * -> near. Transparent above the towers.
 */
export const SKYLINE: SpriteSheet = {
	palette: P,
	anchor: { x: 0, y: 0 },
	frames: {
		far: [
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"....................................................................DDDDDD........................",
			"....................................................................DDDDDD........................",
			"........................DDDD....................................DDDDDDDDDDDDDD....................",
			"........................DDDD....................................DDDDDDDDDDDDDD....................",
			"....................DDDDDDDDDDDDDD..............................DDDDDDDDDDDDDD....................",
			"....................DDDDDDDDDDDDDD..............................DDDDDDDDDDDDDD....................",
			"....................DDDDDDDDDDDDDD..............................DDDBDDDDDDDDDD....................",
			"....................DDDDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDD....................",
			"DDDDDDDDDDDD........DDDBDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDD....................",
			"DDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDD",
			"DDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDD",
			"DDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDBDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDD",
			"DDDADDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDDDD........DDDDDDDDDDDD",
			"DDDDDDDDDDDD........DDDDDDDDDDDDDD........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........DDDBDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDADDDDDD........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........DDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBDDDDDDADDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
			"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
		],
		mid: [
			"................................L.................................................................",
			"................................L.................................................................",
			"................................L.................................................................",
			"..........................LLLLLLLLLLLLLL..........................................................",
			"..........................LLLLLLLLLLLLLL..........................................................",
			"..........................LLLLLLLLLLLLLL................................LLLLLLLLLLLL..............",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL................................LLLLLLLLLLLL..............",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL................................LLLLLLLLLLLL..............",
			"..LLLLLLLLLLLLLL..........LLLDLLLLLLLLLL................................LLLLLccLLLLL..............",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL..............",
			"..LLLmmmmmmmmLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL..............",
			"..LLLmmmmmmmmLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL..............",
			"..LLLmmmmMMmmLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLmmmmmmmmLLL..........LLLLLLLLLDLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLmmmmmmmmLLL..........LLLLLLLLLLLLLL........LLLLDLLLLLLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLMMMMMMMMLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLDLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLDLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLDLLLLLLLL........LLLLLLLLLDLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLccLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLDLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLDLLL........LLLLLLLLLLLLDLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLDLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
			"..LLLLLLLLLLLLLL..........LLLLLLLLLLLLLL........LLLLLLLLLLLLLLLL........LLLLLLLLLLLL......LLLLLLLL",
		],
		near: [
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"..................................................................................................",
			"........................O.........................................................................",
			"........................k.........................................................................",
			"........................k.........................................................................",
			"........................kkk.......................................................................",
			"........................k............................................k............................",
			"........................k............................................kk...........................",
			"......................kkk............................................k............................",
			"........................k............................................k................kkkkk.......",
			"........................k............................................k..................k.........",
			"........................k.........................................kkkkkk................k.........",
			"........................k.........................................kkkkkk................k.........",
			"........kkkkkk..........k.........................................kkkkkk................k.........",
			"........kkkkkk..kkkkkkkkkkkkkkkkkkkkkkkk......kkkkkk..............kkkkkk................k.........",
			"........kkkkkk..kkkkkkkkkkkkkkkkkkkkkkkk......kkkkkk........kkkkkkkkkkkkkkkkkkkk........k.........",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......kkkkkk........kkkkkkkkkkkkkkkkkkkk........k.........",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk........k.........",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
			"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
		],
	},
};

/**
 * 16x24 wall posters: poster.0 glitchy neonViolet/deepMagenta glyphs,
 * poster.1 deepCyan/holoBlue tech diagram.
 */
export const POSTERS: SpriteSheet = {
	palette: P,
	anchor: { x: 0, y: 0 },
	frames: {
		"poster.0": [
			"kkkkkkkkkkkkkkkk",
			"kNNNNNNNNNNNNNNk",
			"kNvvNNNNNNNNMMNk",
			"kNNNvvvvvvvvNNNk",
			"kNNNNNNvvNNNNNNk",
			"kNNNNNNvvNNNNNNk",
			"kNNNvvvvvvvvNNNk",
			"kNNNvvNNNNvvNNNk",
			"kNNNvvNNNNvvNNNk",
			"kNNNvvvvvvvvNNNk",
			"kNNNNNNNNNNNNNNk",
			"kNNvvNNNMMNNvvNk",
			"kNNNMMNNvvNNMMNk",
			"kNNNNNNNNNNNNNNk",
			"kvvvvvvNNNNNNNNk",
			"kNNNNNNNNMMMMMMk",
			"kNNNNNNNNNNNNNNk",
			"kNvvvvNNMMMMNNNk",
			"kNNNNNNNNNNNNNNk",
			"kNvNvvNvNvvvNvNk",
			"kNvNvvNvNvvvNvNk",
			"kNNNNNNNNNNNNNNk",
			"kNNNNNNNNNNvvNNk",
			"kkkkkkkkkkkkkkkk",
		],
		"poster.1": [
			"kkkkkkkkkkkkkkkk",
			"kNNNNNNNNNNNNNNk",
			"kNBBBBBBBBBBBBNk",
			"kNNNNNNNNNNNNNNk",
			"kNNNNNBBBBNNNNNk",
			"kNNNNBNNNNBNNNNk",
			"kNNNBNNNNNNBNNNk",
			"kNNNBNNBBNNBNNNk",
			"kNNNBNNBBNNBNNNk",
			"kNNNBNNNNNNBNNNk",
			"kNNNNBNNNNBNNNNk",
			"kNNNNNBBBBNNNNNk",
			"kNNNNNNCCNNNNNNk",
			"kNNNNNNCCNNNNNNk",
			"kNCCCCCWWCCCCCNk",
			"kNCNNNNNNNNNNCNk",
			"kNCNNNNNNNNNNCNk",
			"kNBNNNNNNNNNNBNk",
			"kNNNNNNNNNNNNNNk",
			"kNWWNBBNNCCCNNNk",
			"kNNNNNNNNNNNNNNk",
			"kNCCCCCCCCCCCCNk",
			"kNNNNNNNNNNNNNNk",
			"kkkkkkkkkkkkkkkk",
		],
	},
};

/**
 * "HERDR" neon wall sign. Letters are 9x12 magenta tubes (2px strokes),
 * stamped onto the 64x20 panel by code at x = 4 + i*12; "off" variants are
 * the dim deepMagenta state. swoosh is a 56x3 neonCyan underline.
 */
export const SIGN: SpriteSheet = {
	palette: P,
	anchor: { x: 0, y: 0 },
	frames: {
		panel: [
			"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDS",
			"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		],
		"h.on": [
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mmmmmmmmm",
			"mmmmmmmmm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
		],
		"h.off": [
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MMMMMMMMM",
			"MMMMMMMMM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
		],
		"e.on": [
			".mmmmmmm.",
			"mmmmmmmmm",
			"mm.......",
			"mm.......",
			"mm.......",
			"mmmmmmm..",
			"mmmmmmm..",
			"mm.......",
			"mm.......",
			"mm.......",
			"mmmmmmmmm",
			".mmmmmmm.",
		],
		"e.off": [
			".MMMMMMM.",
			"MMMMMMMMM",
			"MM.......",
			"MM.......",
			"MM.......",
			"MMMMMMM..",
			"MMMMMMM..",
			"MM.......",
			"MM.......",
			"MM.......",
			"MMMMMMMMM",
			".MMMMMMM.",
		],
		"r.on": [
			"mmmmmmm..",
			"mmmmmmmm.",
			"mm.....mm",
			"mm.....mm",
			"mmmmmmmm.",
			"mmmmmmm..",
			"mm..mm...",
			"mm...mm..",
			"mm...mm..",
			"mm....mm.",
			"mm....mm.",
			"mm.....mm",
		],
		"r.off": [
			"MMMMMMM..",
			"MMMMMMMM.",
			"MM.....MM",
			"MM.....MM",
			"MMMMMMMM.",
			"MMMMMMM..",
			"MM..MM...",
			"MM...MM..",
			"MM...MM..",
			"MM....MM.",
			"MM....MM.",
			"MM.....MM",
		],
		"d.on": [
			"mmmmmmm..",
			"mmmmmmmm.",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mm.....mm",
			"mmmmmmmm.",
			"mmmmmmm..",
		],
		"d.off": [
			"MMMMMMM..",
			"MMMMMMMM.",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MM.....MM",
			"MMMMMMMM.",
			"MMMMMMM..",
		],
		"r2.on": [
			"mmmmmmm..",
			"mmmmmmmm.",
			"mm.....mm",
			"mm.....mm",
			"mmmmmmmm.",
			"mmmmmmm..",
			"mm..mm...",
			"mm...mm..",
			"mm...mm..",
			"mm....mm.",
			"mm....mm.",
			"mm.....mm",
		],
		"r2.off": [
			"MMMMMMM..",
			"MMMMMMMM.",
			"MM.....MM",
			"MM.....MM",
			"MMMMMMMM.",
			"MMMMMMM..",
			"MM..MM...",
			"MM...MM..",
			"MM...MM..",
			"MM....MM.",
			"MM....MM.",
			"MM.....MM",
		],
		swoosh: [
			"..................................cccccccccccccccccccccc",
			"..............cccccccccccccccccccccccccccc..............",
			"cccccccccccccccccccccc..................................",
		],
	},
};

/**
 * 12x8 steel wall vent with ink slits.
 */
export const VENT: SpriteSheet = {
	palette: P,
	anchor: { x: 0, y: 0 },
	frames: {
		vent: [
			"kkkkkkkkkkkk",
			"kSSSSSSSSSSk",
			"kSkkkkkkkkSk",
			"kSSSSSSSSSSk",
			"kSkkkkkkkkSk",
			"kSSSSSSSSSSk",
			"kLkkkkkkkkLk",
			"kkkkkkkkkkkk",
		],
	},
};
